name: WikiCraft
version: '0.1.0-SNAPSHOT'
main: io.github.iherongh.wikicraft.WikiCraft
api-version: '1.21'
author: iHeron
description: Integrates MediaWiki searching into Minecraft.

libraries:
  - io.github.fastily:jwiki:1.11.0
