name: Version Update

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New semantic version (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate version input
        run: |
          if ! [[ "${{ inputs.new_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in semantic version format (X.Y.Z)"
            exit 1
          fi

      - name: Update plugin.yml version
        run: |
          sed -i "s/^version: .*/version: ${{ inputs.new_version }}/" src/main/resources/plugin.yml

      - name: Update gradle.properties version
        run: |
          sed -i "s/^version=.*/version=${{ inputs.new_version }}/" gradle.properties

      - name: Commit version updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/main/resources/plugin.yml gradle.properties
          git commit -m "Update version to ${{ inputs.new_version }} [skip ci]"
          git push
